api: 
  url: https://apptwo.contrastsecurity.com/Contrast
  api_key: 9Xhur2FW4eK17pq7XNlO7uZ3L39LRdEA
  service_key: HGY4GC2S89WTA7XE
  user_name: agent_ac0ec4e6-f84a-46b5-8534-7a3a14632bf8@Ddooleysohsofantasticorg
agent:
  java:
    standalone_app_name: openshift-juice-shop
application:
  name: openshift-juice-shop
